### list all messages
GET http://localhost:3000/messages

### create a new message
POST http://localhost:3000/messages
Content-Type: application/json

{
  "contents": "hi there"
}

### get a message
GET http://localhost:3000/messages/123